### ISSUE TITLE
Workshops

### ISSUE THREAD

**Issue by tpiros** [fromthefront/ama#3]
Hi,

Do you plan on having workshops in the '16 edition of your conference?

Thanks!

**Comment by cedmax** [comment]
Hi @tamaspiros, 
this was actually the very first question we got in here (ref: https://github.com/fromthefront/ama/issues/1), but that of course means there is some interest for it. 

TL;DR: we haven't planned them for the moment and it's very likely we won't have any, but the door is not closed yet, if you get what I mean.
