### ISSUE TITLE
Volunteering at conferences

### ISSUE THREAD

**Issue by CarlMungazi** [fromthefront/ama#8]
I've been looking for conferences to volunteer at in the UK and Europe but have had no luck so far. In your view, what is the best way to find such opportunities and bring value to a team if you became a volunteer?

**Comment by cedmax** [comment]
Hi Carl, it really depends what you mean with volunteering: are you talking about helping out the day of the event or becoming part of the organising team?

The first might be the easier to start with: be bold and get in touch with the organisers, explain why you want to volunteer (someone could think you are trying to consume the conference without getting a ticket, so be open and honest about your goals and why you want to help).

The latter might be a little trickier on a short term: most organising teams have already their balance or their "pool" of people in the community of reference (or the people volunteering at the event) when they need help. 

I guess you could start helping out a local meetup/event and try to build relationships and see how it goes: when it comes to no-profit events, working with people you trust already makes everything smoother. 

I hope I sparkled some ideas, sorry for not having a "recipe" for this.
